import { AnalysisResult, VerdictInfo, AIDetectorConfig } from '@/types/ai-detector';
import { detectAIContent } from './ai-detector-engine';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { toast } from 'sonner';

// Default configuration
const defaultConfig: AIDetectorConfig = {
  sensitivityLevel: 'medium',
  minTextLength: 50,
};

// Get verdict based on score
export const getVerdict = (score: number): VerdictInfo => {
  if (score >= 85) {
    return {
      text: `Very likely AI-generated (${Math.round(score)}% AI, ${Math.round(100 - score)}% Human)`,
      className: "text-red-500"
    };
  } else if (score >= 70) {
    return {
      text: `Likely AI-generated (${Math.round(score)}% AI, ${Math.round(100 - score)}% Human)`,
      className: "text-orange-500"
    };
  } else if (score >= 50) {
    return {
      text: `Possibly AI-generated (${Math.round(score)}% AI, ${Math.round(100 - score)}% Human)`,
      className: "text-yellow-500"
    };
  } else if (score >= 30) {
    return {
      text: `Likely human-written (${Math.round(score)}% AI, ${Math.round(100 - score)}% Human)`,
      className: "text-green-400"
    };
  } else {
    return {
      text: `Very likely human-written (${Math.round(score)}% AI, ${Math.round(100 - score)}% Human)`,
      className: "text-green-600"
    };
  }
};

// Generate more detailed summary based on score
const getDetailedSummary = (score: number): string => {
  if (score >= 85) {
    return "This text is very likely AI-generated. It exhibits numerous patterns consistent with content created by large language models — including uniform sentence structure, predictable transitions, formulaic phrases, and statistically smooth writing. The text shows low burstiness and high readability consistency, hallmarks of AI authorship.";
  } else if (score >= 70) {
    return "This text is likely AI-generated. It shows significant markers of AI writing patterns including consistent sentence complexity, AI-typical vocabulary choices, and formulaic phrases. While some portions may have been edited by a human, the overall structure strongly suggests AI involvement.";
  } else if (score >= 50) {
    return "This text shows mixed characteristics with significant AI influence. Our analysis indicates it may be a combination of AI-generated content and human editing, or created using AI writing assistants with substantial human guidance. The text contains some patterns found in AI content but also shows variability that could indicate human involvement.";
  } else if (score >= 30) {
    return "This text is likely primarily human-written with possible minor AI assistance. It shows mostly natural language patterns with occasional characteristics that might indicate limited AI involvement. The writing demonstrates natural burstiness and vocabulary diversity characteristic of human authorship.";
  } else {
    return "This text is very likely human-written. It demonstrates natural language patterns, stylistic diversity, and burstiness that are difficult for AI to replicate. The content shows creative expression and writing patterns that differ significantly from AI-generated text.";
  }
};

// Generate PDF report
export const generateReportPDF = (result: AnalysisResult): void => {
  const verdict = getVerdict(result.overallScore);
  const doc = new jsPDF();

  // Header
  doc.setFillColor(240, 240, 245);
  doc.rect(0, 0, 210, 40, 'F');

  // Watermark
  doc.setFont("helvetica", "italic");
  doc.setFontSize(60);
  doc.setTextColor(245, 245, 250);
  doc.text("aitextverifier.com", 105, 150, { align: "center", angle: 45 });

  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 20, 70);
  doc.setFontSize(20);
  doc.text("AI Content Detection Report", 105, 20, { align: "center" });
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 120);
  doc.text("Generated by AITextVerifier.com", 105, 28, { align: "center" });
  doc.text(new Date().toLocaleString(), 105, 35, { align: "center" });

  // Verdict section
  doc.setDrawColor(200, 200, 220);
  doc.setLineWidth(0.5);
  doc.line(20, 45, 190, 45);

  doc.setFontSize(14);
  doc.setTextColor(20, 20, 70);
  doc.setFont("helvetica", "bold");
  doc.text("Overall Analysis", 20, 55);

  const verdictColor =
    result.overallScore > 70 ? [220, 50, 50] :
      result.overallScore > 30 ? [240, 150, 50] : [50, 180, 80];

  doc.setFillColor(verdictColor[0], verdictColor[1], verdictColor[2]);
  doc.circle(35, 70, 8, 'F');

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(verdictColor[0], verdictColor[1], verdictColor[2]);
  doc.text(verdict.text, 50, 70);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 100);
  doc.text(`AI Content Probability: ${result.overallScore.toFixed(1)}%`, 50, 78);

  // Detection Methods breakdown
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(20, 20, 70);
  doc.text("Detection Methods Breakdown", 20, 95);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 100);

  const methods = result.detectionMethods;
  const methodNames = [
    ['Entropy Analysis', methods.entropyAnalysis],
    ['Vocabulary Diversity', methods.vocabularyDiversity],
    ['Sentence Structure', methods.sentenceStructure],
    ['Burstiness', methods.burstiness],
    ['Formulaic Phrases', methods.formulaicPhrases],
    ['Readability Consistency', methods.readabilityConsistency],
  ];

  let yPos = 105;
  for (const [name, score] of methodNames) {
    doc.text(`${name}: ${(score as number).toFixed(0)}%`, 25, yPos);
    yPos += 8;
  }

  // Summary
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(20, 20, 70);
  doc.text("Analysis Summary", 20, yPos + 10);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 100);

  const summaryLines = doc.splitTextToSize(result.summary, 170);
  doc.text(summaryLines, 20, yPos + 20);

  // Analyzed Text
  yPos = yPos + 20 + summaryLines.length * 6 + 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(20, 20, 70);
  doc.text("Analyzed Text", 20, yPos);

  const textLines = doc.splitTextToSize(result.originalText || "", 160);

  if (textLines.length > 0) {
    (doc as any).autoTable({
      startY: yPos + 5,
      head: [['Text Analysis']],
      body: [[textLines.join('\n')]],
      theme: 'plain',
      styles: {
        cellPadding: 6,
        fontSize: 12,
        textColor: [50, 50, 70],
        fontStyle: 'normal'
      },
      headStyles: {
        fillColor: [240, 240, 250],
        textColor: [50, 50, 100],
        fontStyle: 'bold'
      }
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 170);
    doc.text(`Page ${i} of ${pageCount} | AITextVerifier.com`, 105, 292, { align: "center" });
  }

  doc.save('ai-detection-report.pdf');
};

// Analyze text function — now uses the unified LLM backend (Groq/Llama 3.3)
export const analyzeText = async (text: string, config: Partial<AIDetectorConfig> = {}): Promise<AnalysisResult> => {
  const mergedConfig: AIDetectorConfig = { ...defaultConfig, ...config };

  try {
    if (!text || text.trim().length < mergedConfig.minTextLength) {
      const message = "Text is too short for accurate analysis";
      toast.error(message);
      throw new Error(message);
    }

    console.log("Sending text to LLM AI detection engine, text length:", text.length);

    // Call the unified LLM edge function
    const { supabase } = await import('@/integrations/supabase/client');
    const { data, error } = await supabase.functions.invoke('process-llm', {
      body: {
        tool: 'aidetect',
        text: text
      }
    });

    if (error) {
      console.error("Supabase edge function error:", error);
      throw new Error(error.message || "Failed to analyze text using AI engine");
    }

    if (!data || data.error) {
      throw new Error(data?.error || "No data returned from AI engine");
    }

    console.log("LLM AI Detection result received:", data.overallScore, "Provider:", data._provider);

    // Generate detailed summary
    const summary = getDetailedSummary(data.overallScore || 0);

    // Mock sentences to prevent UI mapping crashes in VerdictDisplay
    const mockSentences = [{
      text: text,
      aiProbability: data.overallScore || 0,
      isHuman: (data.overallScore || 0) < 50,
      features: {
        entropy: 0,
        vocabularyScore: 0,
        formulaicScore: 0,
        readabilityScore: 0,
        structureScore: 0,
        burstyScore: 0,
      }
    }];

    // Build the final result enforcing the LLM EngineResult json type map
    const result: AnalysisResult = {
      sentences: mockSentences,
      overallScore: data.overallScore || 0,
      summary,
      detectionMethods: {
        entropyAnalysis: data.detectionMethods?.entropyAnalysis || 0,
        vocabularyDiversity: data.detectionMethods?.vocabularyDiversity || 0,
        sentenceStructure: data.detectionMethods?.sentenceStructure || 0,
        burstiness: data.detectionMethods?.burstiness || 0,
        formulaicPhrases: data.detectionMethods?.formulaicPhrases || 0,
        readabilityConsistency: data.detectionMethods?.readabilityConsistency || 0,
      },
      highlightedSentences: data.highlightedSentences || [],
      improvedVersion: data.improvedVersion || "",
      originalText: text,
    };

    console.log("Analysis complete with score:", result.overallScore);
    return result;
  } catch (error) {
    console.error("Error in analyzeText:", error);
    throw error;
  }
};

// Download report
export const downloadTextAsFile = (text: string, filename: string) => {
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// Text report for backwards compatibility
export const generateReportText = (result: AnalysisResult): string => {
  const verdict = getVerdict(result.overallScore);

  let report = `AI CONTENT DETECTION REPORT\n`;
  report += `==========================\n\n`;
  report += `Overall Score: ${result.overallScore.toFixed(1)}% (${verdict.text})\n\n`;
  report += `Summary: ${result.summary}\n\n`;

  report += `\nDETECTION METHODS BREAKDOWN\n`;
  report += `------------------\n`;
  report += `Entropy Analysis: ${result.detectionMethods.entropyAnalysis.toFixed(0)}%\n`;
  report += `Vocabulary Diversity: ${result.detectionMethods.vocabularyDiversity.toFixed(0)}%\n`;
  report += `Sentence Structure: ${result.detectionMethods.sentenceStructure.toFixed(0)}%\n`;
  report += `Burstiness: ${result.detectionMethods.burstiness.toFixed(0)}%\n`;
  report += `Formulaic Phrases: ${result.detectionMethods.formulaicPhrases.toFixed(0)}%\n`;
  report += `Readability Consistency: ${result.detectionMethods.readabilityConsistency.toFixed(0)}%\n`;

  if (result.highlightedSentences.length > 0) {
    report += `\nAI-FLAGGED SENTENCES\n`;
    report += `------------------\n`;
    result.highlightedSentences.forEach((s, i) => {
      report += `${i + 1}. ${s}\n`;
    });
  }

  report += `\nReport generated on: ${new Date().toLocaleString()}\n`;
  return report;
};
