
// Function to generate more detailed analysis summary as bullet points
export const getExpandedSummaryPoints = (score: number): string[] => {
  if (score >= 85) {
    return [
      "This text is very likely AI-generated according to our analysis.",
      "It exhibits numerous patterns consistent with content created by large language models like ChatGPT, Claude, or Gemini.",
      "The text contains stylistic elements typical of AI writing, including uniform sentence structure and predictable transitions.",
      "It may be entirely generated by an AI system or could be the result of content spinning tools.",
      "Many organizations now use AI tools like ChatGPT or Copy.ai to automate content creation."
    ];
  } else if (score >= 70) {
    return [
      "This text is likely AI-generated according to our analysis.",
      "It shows significant markers of AI writing patterns consistent with tools like ChatGPT.",
      "While some portions may have been edited by a human, the overall structure suggests AI involvement.",
      "The content might have been generated using AI writing assistants with minimal human editing.",
      "The uniformity of style and predictable language patterns are consistent with AI-generated text."
    ];
  } else if (score >= 50) {
    return [
      "This text shows mixed characteristics with significant AI influence.",
      "Our analysis indicates it may be a combination of AI-generated content and human editing.",
      "The text contains patterns found in content from tools like ChatGPT or Claude, but shows some variability.",
      "It may be the result of content rephrasing tools that use AI to modify existing human-written text.",
      "This hybrid approach to content creation is becoming increasingly common in professional environments."
    ];
  } else if (score >= 30) {
    return [
      "This text is likely primarily human-written with some AI assistance.",
      "Our analysis shows it contains mostly natural language patterns with occasional AI characteristics.",
      "The writer may have used AI tools for grammar checking, sentence rephrasing, or brainstorming.",
      "The inconsistencies and nuances in the writing style are more characteristic of human writing.",
      "Many professional writers now use tools like Grammarly or ProWritingAid, which might explain some polished elements."
    ];
  } else {
    return [
      "This text is very likely human-written according to our analysis.",
      "It demonstrates natural language patterns, stylistic inconsistencies, and linguistic nuances.",
      "The content shows creative expression and unique perspective that are difficult for AI tools to replicate.",
      "While the writer may have used basic AI tools for proofreading, the core content appears authentically human.",
      "The personal voice, original thinking patterns, and variations in tone are consistent with genuine human writing."
    ];
  }
};
