
import React, { useEffect, useState } from 'react';
import { Layout } from '@/components/Layout';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Search, CheckCircle, FileText, Languages, Bot, Code, Database, Lock, Server } from 'lucide-react';
import { Input } from '@/components/ui/input';

const KnowledgeBase = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const categories = [
    { id: 'all', name: 'All Topics' },
    { id: 'detector', name: 'AI Detection', icon: <Bot className="h-4 w-4" /> },
    { id: 'grammar', name: 'Grammar Checker', icon: <CheckCircle className="h-4 w-4" /> },
    { id: 'summary', name: 'AI Summary', icon: <FileText className="h-4 w-4" /> },
    { id: 'translation', name: 'Translation', icon: <Languages className="h-4 w-4" /> },
    { id: 'technical', name: 'Technical', icon: <Code className="h-4 w-4" /> }
  ];

  const articles = [
    {
      id: 1,
      title: 'How AI Content Detection Works',
      category: 'detector',
      content: `
        <p>Our AI detection system uses a proprietary algorithm that analyzes text across multiple dimensions to determine whether it was written by an AI system or a human.</p>
        
        <h3>Key Components of Our Detection Engine</h3>
        <p>The detection algorithm operates through several sophisticated analysis layers:</p>
        <ul>
          <li><strong>Statistical Pattern Recognition:</strong> The system analyzes statistical patterns in text that distinguish between human and machine writing styles.</li>
          <li><strong>Linguistic Feature Analysis:</strong> We examine unique linguistic markers, syntactic structures, and semantic coherence.</li>
          <li><strong>Contextual Understanding:</strong> Our algorithm evaluates contextual consistency and logical flow of arguments.</li>
          <li><strong>Perplexity and Burstiness Assessment:</strong> We measure text entropy patterns that differ between human and AI writers.</li>
        </ul>
        
        <h3>Scoring Mechanism</h3>
        <p>The analysis produces a score from 0-100, representing the probability that content was generated by AI:</p>
        <ul>
          <li>90-100%: Very likely AI-generated</li>
          <li>70-89%: High probability of AI involvement</li>
          <li>40-69%: Mixed indicators</li>
          <li>0-39%: Likely human-written</li>
        </ul>
        
        <h3>Continuous Improvement</h3>
        <p>Our detection technology undergoes constant refinement through:</p>
        <ul>
          <li>Regular model updates to keep pace with evolving AI writing systems</li>
          <li>Training on diverse content corpuses across multiple domains and writing styles</li>
          <li>Validation testing against known human and AI-written samples</li>
        </ul>
      `,
      excerpt: 'Understand the sophisticated technology behind our AI content detection system.'
    },
    {
      id: 2,
      title: 'Grammar Checker Technology Explained',
      category: 'grammar',
      content: `
        <p>Our grammar checking system combines rule-based checking with statistical analysis to provide comprehensive grammar, style, and spelling corrections.</p>
        
        <h3>Core Technology Components</h3>
        <p>The grammar checking system utilizes several advanced natural language processing techniques:</p>
        <ul>
          <li><strong>Deep Linguistic Analysis:</strong> We parse text to understand sentence structure, parts of speech, and grammatical relationships.</li>
          <li><strong>Contextual Error Detection:</strong> Our system identifies errors based on context, not just isolated rules.</li>
          <li><strong>Style Enhancement:</strong> Beyond grammar, we analyze readability, tone consistency, and word choice.</li>
          <li><strong>Domain-Specific Checking:</strong> We apply different rule sets for academic, business, creative, or technical writing.</li>
        </ul>
        
        <h3>Correction Process</h3>
        <p>The grammar checking process follows these steps:</p>
        <ol>
          <li>Text tokenization and parsing</li>
          <li>Rule application and pattern matching</li>
          <li>Statistical model evaluation</li>
          <li>Context-aware suggestion generation</li>
          <li>Final result ranking and presentation</li>
        </ol>
        
        <h3>Technical Implementation</h3>
        <p>Our grammar checker is built on a hybrid architecture that includes:</p>
        <ul>
          <li>Comprehensive linguistic rule database with over 20,000 grammar patterns</li>
          <li>Machine learning models trained on diverse writing samples</li>
          <li>Real-time processing infrastructure for instant feedback</li>
          <li>Regular updates to improve accuracy and coverage</li>
        </ul>
      `,
      excerpt: 'Discover how our grammar checking system identifies and corrects writing issues.'
    },
    {
      id: 3,
      title: 'Text Summarization Methodology',
      category: 'summary',
      content: `
        <p>Our summarization tool employs extractive and abstractive techniques to create concise, accurate summaries while preserving key information.</p>
        
        <h3>Summarization Approaches</h3>
        <p>Our system uses a hybrid approach combining multiple methods:</p>
        <ul>
          <li><strong>Extractive Summarization:</strong> Identifies and extracts the most important sentences from the original text.</li>
          <li><strong>Abstractive Processing:</strong> Generates new sentences that capture key concepts in a condensed form.</li>
          <li><strong>Topic Modeling:</strong> Identifies main themes and ensures they're represented in the summary.</li>
          <li><strong>Semantic Coherence:</strong> Ensures the summary flows logically and maintains coherence.</li>
        </ul>
        
        <h3>Customization Options</h3>
        <p>Users can customize the summarization process with options for:</p>
        <ul>
          <li>Summary length (percentage of original text or word/sentence count)</li>
          <li>Focus areas or keywords to prioritize</li>
          <li>Output style (bullet points, narrative, etc.)</li>
          <li>Domain specialization (academic, news, technical)</li>
        </ul>
        
        <h3>Technical Implementation</h3>
        <p>Our summarization engine utilizes:</p>
        <ul>
          <li>Advanced natural language understanding models</li>
          <li>Proprietary algorithms for information ranking</li>
          <li>Content restructuring techniques for improved readability</li>
          <li>Quality assurance processes to ensure accuracy</li>
        </ul>
      `,
      excerpt: 'Learn about the technology that powers our text summarization tool.'
    },
    {
      id: 4,
      title: 'Translation System Architecture',
      category: 'translation',
      content: `
        <p>Our translation system combines neural machine translation with specialized linguistic models to deliver accurate, contextually appropriate translations across multiple languages.</p>
        
        <h3>Core Translation Technology</h3>
        <p>Our translation engine builds on several advanced components:</p>
        <ul>
          <li><strong>Neural Translation Models:</strong> Deep learning architectures specifically designed for language translation tasks.</li>
          <li><strong>Specialized Language Pairs:</strong> Custom-trained models for each language pair to capture unique linguistic relationships.</li>
          <li><strong>Context-Aware Processing:</strong> Analysis of surrounding text to ensure appropriate word choices and expressions.</li>
          <li><strong>Domain Adaptation:</strong> Specialized handling for technical, medical, legal, and other domain-specific content.</li>
        </ul>
        
        <h3>Translation Process</h3>
        <p>Text undergoes a multi-stage translation process:</p>
        <ol>
          <li>Source language analysis and preprocessing</li>
          <li>Initial translation generation</li>
          <li>Refinement and post-processing</li>
          <li>Quality scoring and confidence assessment</li>
          <li>Final output formatting</li>
        </ol>
        
        <h3>Supported Languages</h3>
        <p>Our system supports over 40 languages with varying levels of capability:</p>
        <ul>
          <li>Tier 1 (highest quality): English, Spanish, French, German, Japanese, Chinese</li>
          <li>Tier 2: Italian, Portuguese, Russian, Korean, Arabic, Dutch</li>
          <li>Tier 3: Additional languages with good quality but potentially fewer features</li>
        </ul>
      `,
      excerpt: 'Explore the sophisticated translation system that powers our language tools.'
    },
    {
      id: 5,
      title: 'Database Architecture and Performance',
      category: 'technical',
      content: `
        <p>Our platform utilizes a multi-tiered database architecture designed for high performance, scalability, and data security.</p>
        
        <h3>Database System Design</h3>
        <p>The database architecture includes:</p>
        <ul>
          <li><strong>Relational Data Store:</strong> For structured user data, account information, and transaction records</li>
          <li><strong>Document Database:</strong> For storing and analyzing text content and processing results</li>
          <li><strong>Vector Database:</strong> For semantic search and similarity matching</li>
          <li><strong>Cache Layer:</strong> For high-speed access to frequently used data</li>
        </ul>
        
        <h3>Performance Optimizations</h3>
        <p>Several techniques ensure responsive performance:</p>
        <ul>
          <li>Query optimization and indexing strategies</li>
          <li>Data partitioning and sharding for horizontal scaling</li>
          <li>Read replicas for distributing query loads</li>
          <li>Connection pooling and query batching</li>
        </ul>
        
        <h3>Data Security Measures</h3>
        <p>Our database security approach includes:</p>
        <ul>
          <li>Encryption of data at rest and in transit</li>
          <li>Role-based access control with least privilege principles</li>
          <li>Regular security audits and vulnerability assessments</li>
          <li>Compliance with data protection regulations</li>
        </ul>
      `,
      excerpt: 'A technical overview of our database architecture and optimization strategies.'
    },
    {
      id: 6,
      title: 'API Architecture and Integration',
      category: 'technical',
      content: `
        <p>Our API architecture follows RESTful design principles, with secure endpoints for all major platform features.</p>
        
        <h3>API Design Philosophy</h3>
        <p>Our API development follows these core principles:</p>
        <ul>
          <li><strong>Resource-Oriented Design:</strong> Clear, intuitive endpoint structures based on resources</li>
          <li><strong>Consistent Patterns:</strong> Uniform request/response formats and error handling</li>
          <li><strong>Versioning:</strong> Clear versioning to ensure backward compatibility</li>
          <li><strong>Documentation:</strong> Comprehensive documentation with examples and use cases</li>
        </ul>
        
        <h3>Authentication and Security</h3>
        <p>API security measures include:</p>
        <ul>
          <li>API key authentication for basic access</li>
          <li>OAuth 2.0 for user-authorized integrations</li>
          <li>Rate limiting to prevent abuse</li>
          <li>HTTPS encryption for all API traffic</li>
        </ul>
        
        <h3>Integration Capabilities</h3>
        <p>Our API supports various integration scenarios:</p>
        <ul>
          <li>Content management system plugins</li>
          <li>Custom workflow integrations</li>
          <li>Batch processing for high-volume needs</li>
          <li>Webhook notifications for event-driven architectures</li>
        </ul>
      `,
      excerpt: 'Understand our API design, security measures, and integration capabilities.'
    },
    {
      id: 7,
      title: 'Security Infrastructure Overview',
      category: 'technical',
      content: `
        <p>Our comprehensive security infrastructure protects user data, system integrity, and service availability through multiple layers of controls.</p>
        
        <h3>Security Architecture</h3>
        <p>Our security framework includes:</p>
        <ul>
          <li><strong>Network Security:</strong> Firewall protection, intrusion detection/prevention, and traffic monitoring</li>
          <li><strong>Application Security:</strong> Secure coding practices, dependency scanning, and regular security testing</li>
          <li><strong>Data Protection:</strong> Encryption, access controls, and data minimization practices</li>
          <li><strong>Infrastructure Security:</strong> Hardened systems, least-privilege configurations, and regular updates</li>
        </ul>
        
        <h3>Authentication and Access Control</h3>
        <p>User security features include:</p>
        <ul>
          <li>Multi-factor authentication options</li>
          <li>Role-based access control</li>
          <li>Session management with secure timeout policies</li>
          <li>Password policies enforcing strong credentials</li>
        </ul>
        
        <h3>Monitoring and Incident Response</h3>
        <p>Our security operations include:</p>
        <ul>
          <li>24/7 monitoring of systems and network traffic</li>
          <li>Automated alerts for suspicious activities</li>
          <li>Defined incident response procedures</li>
          <li>Regular security drills and tabletop exercises</li>
        </ul>
      `,
      excerpt: 'A detailed look at our multi-layered security infrastructure and practices.'
    },
  ];

  const filteredArticles = articles.filter(article => {
    const matchesSearch = searchQuery === '' || 
      article.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      article.excerpt.toLowerCase().includes(searchQuery.toLowerCase());
    
    const matchesCategory = selectedCategory === 'all' || article.category === selectedCategory;
    
    return matchesSearch && matchesCategory;
  });

  return (
    <Layout>
      <div className="container mx-auto px-4 py-12">
        <div className="text-center mb-10">
          <h1 className="text-4xl font-bold mb-4">Knowledge Base</h1>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Explore detailed articles about our technology stack and features
          </p>
        </div>

        <div className="max-w-4xl mx-auto mb-10">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground" />
            <Input 
              placeholder="Search articles..." 
              className="pl-10 py-6 text-lg" 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
        </div>

        <div className="max-w-5xl mx-auto">
          <Tabs defaultValue="all" onValueChange={setSelectedCategory}>
            <TabsList className="grid grid-cols-3 md:grid-cols-6 mb-8">
              {categories.map(category => (
                <TabsTrigger key={category.id} value={category.id} className="flex items-center gap-1">
                  {category.icon} {category.name}
                </TabsTrigger>
              ))}
            </TabsList>
            
            {categories.map(category => (
              <TabsContent key={category.id} value={category.id}>
                {filteredArticles.length > 0 ? (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {filteredArticles.map(article => (
                      <Card key={article.id} className="h-full hover:shadow-md transition-shadow">
                        <CardHeader>
                          <CardTitle>{article.title}</CardTitle>
                          <CardDescription>{article.excerpt}</CardDescription>
                        </CardHeader>
                        <CardContent className="prose prose-slate dark:prose-invert max-w-none" dangerouslySetInnerHTML={{ __html: article.content }} />
                      </Card>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-8">
                    <p className="text-muted-foreground">No articles found matching your search criteria.</p>
                  </div>
                )}
              </TabsContent>
            ))}
          </Tabs>
        </div>

        <div className="max-w-3xl mx-auto mt-20 text-center">
          <h2 className="text-2xl font-bold mb-3">Technical Stack Overview</h2>
          <p className="text-muted-foreground mb-8">Our platform is built on a modern, scalable technology stack</p>
          
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <div className="p-6 rounded-xl border bg-card hover:shadow-md transition-shadow">
              <Server className="w-8 h-8 text-primary mx-auto mb-3" />
              <h3 className="font-medium mb-2">Backend Infrastructure</h3>
              <p className="text-sm text-muted-foreground">High-performance service architecture with robust caching</p>
            </div>
            <div className="p-6 rounded-xl border bg-card hover:shadow-md transition-shadow">
              <Database className="w-8 h-8 text-primary mx-auto mb-3" />
              <h3 className="font-medium mb-2">Data Management</h3>
              <p className="text-sm text-muted-foreground">Scalable database systems with optimized query performance</p>
            </div>
            <div className="p-6 rounded-xl border bg-card hover:shadow-md transition-shadow">
              <Lock className="w-8 h-8 text-primary mx-auto mb-3" />
              <h3 className="font-medium mb-2">Security Layer</h3>
              <p className="text-sm text-muted-foreground">Enterprise-grade security with encryption and access controls</p>
            </div>
            <div className="p-6 rounded-xl border bg-card hover:shadow-md transition-shadow">
              <Code className="w-8 h-8 text-primary mx-auto mb-3" />
              <h3 className="font-medium mb-2">Frontend Framework</h3>
              <p className="text-sm text-muted-foreground">Modern, responsive UI built with React and Tailwind CSS</p>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default KnowledgeBase;
