
import React from 'react';
import { Lightbulb, CheckCircle, Search, Bot } from 'lucide-react';
import { FlickeringGrid } from '@/components/ui/flickering-grid';

export const AdvancedFeatures: React.FC = () => {
  return (
    <div className="relative bg-gradient-to-b from-blue-50 to-white py-16 overflow-hidden">
      <div className="absolute inset-0 pointer-events-none">
        <FlickeringGrid
          className="absolute inset-0"
          squareSize={4}
          gridGap={6} 
          color="#8B5CF6"
          maxOpacity={0.05}
          flickerChance={0.05}
        />
      </div>
      
      <div className="container mx-auto px-4 relative z-10">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-primary to-primary/90">Advanced Detection Technology</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Our AI detector uses cutting-edge techniques to accurately identify content generated by popular AI models.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="bg-white/90 backdrop-blur-sm rounded-lg p-6 shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
            <div className="flex justify-center items-center h-12 w-12 rounded-full bg-primary/10 text-primary mb-4 mx-auto">
              <Bot className="h-6 w-6" />
            </div>
            <h3 className="text-lg font-semibold text-center mb-2">AI Pattern Recognition</h3>
            <p className="text-muted-foreground text-center text-sm">
              Our system identifies unique patterns and signatures left by AI models like ChatGPT, Claude, and Gemini.
            </p>
          </div>
          
          <div className="bg-white/90 backdrop-blur-sm rounded-lg p-6 shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
            <div className="flex justify-center items-center h-12 w-12 rounded-full bg-primary/10 text-primary mb-4 mx-auto">
              <Lightbulb className="h-6 w-6" />
            </div>
            <h3 className="text-lg font-semibold text-center mb-2">Semantic Analysis</h3>
            <p className="text-muted-foreground text-center text-sm">
              Deep semantic analysis examines content structure, vocabulary patterns, and phrase repetition characteristic of AI writing.
            </p>
          </div>
          
          <div className="bg-white/90 backdrop-blur-sm rounded-lg p-6 shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
            <div className="flex justify-center items-center h-12 w-12 rounded-full bg-primary/10 text-primary mb-4 mx-auto">
              <Search className="h-6 w-6" />
            </div>
            <h3 className="text-lg font-semibold text-center mb-2">Content Fingerprinting</h3>
            <p className="text-muted-foreground text-center text-sm">
              Our proprietary fingerprinting technology identifies subtle markers that distinguish AI-generated content from human writing.
            </p>
          </div>
          
          <div className="bg-white/90 backdrop-blur-sm rounded-lg p-6 shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
            <div className="flex justify-center items-center h-12 w-12 rounded-full bg-primary/10 text-primary mb-4 mx-auto">
              <CheckCircle className="h-6 w-6" />
            </div>
            <h3 className="text-lg font-semibold text-center mb-2">Continuous Learning</h3>
            <p className="text-muted-foreground text-center text-sm">
              Our detection models continuously improve through machine learning, staying up-to-date with the latest AI writing technologies.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
