// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxlqqofwetpycafstjth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4bHFxb2Z3ZXRweWNhZnN0anRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MTc4NTksImV4cCI6MjA1NzM5Mzg1OX0.AtaLmRjayFg1cihvdodN9mdrt2wlzJ9qybYLao2Qb_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);